<a href="https://colab.research.google.com/github/mervegb/numpy/blob/main/tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3], dtype='int32')

b = np.array([[9.0, 8.0,7.0],[6.0, 5.0, 4.0]])

b.shape #2 rows 3 cols (2,3)

(2, 3)

In [4]:
a = np.array([[1,2,3,4,5,6,7,8],[8,9,10,11,12,13,14,15]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [5]:
#get specific element [r,c]
a[1,5]

13

In [6]:
#get a specific column
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
#get specific column
a[:,2]

array([ 3, 10])

In [8]:
#[startindex:endindex:stepsize]
a[0,1:-1:2]
#0 selects the first row
#from this row, start at index 1, go up to but not including the last element
#and take every second element

array([2, 4, 6])

In [10]:
#3d example
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
#get specific element (work outside in)
c[0,1,1]

4

In [13]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [21]:
#replace
c[:,1,:] = [[9,9],[8,8]]
c

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [36]:
#all 0s matrix
#2 -> there are 2 separate blocks
#3 -> 3 rows
#4 -> 4 cols
#adding number at the beginning of tuple adds new outer layer dimension to the array
#adding number at the end of tuple expands the array at its deepest level
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
#all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [40]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.87150001, 0.55186619, 0.60418409],
        [0.59654551, 0.01878721, 0.74939167]],

       [[0.24705061, 0.38808561, 0.81784772],
        [0.44934716, 0.65579513, 0.37741391]],

       [[0.29712987, 0.89537387, 0.74333336],
        [0.38118365, 0.23012932, 0.92401667]],

       [[0.49255061, 0.50690918, 0.74878622],
        [0.28098312, 0.03456823, 0.46015533]]])

In [46]:
#Random integer values
np.random.randint(6, size=(3,3))

array([[2, 0, 5],
       [3, 4, 2],
       [0, 0, 2]])

In [47]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
output = np.ones((5,5))
z = np.zeros((3,3,))

z[1,1] = 9

output[1:4, 1:4,] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
a = np.array([1,2,3])
b = a #we are pointing the same exact thing a is pointing, so if you change b it will change a

#so you can use copy()
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

In [63]:
#mathematics
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [67]:
#Linear algebra
a = np.ones((2,3))
b = np.full((3,2),2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [70]:
#Statistics
stats = np.array([[1,2,3], [4,5,6]])

np.min(stats) #1
np.max(stats) #6

6

In [72]:
np.sum(stats)

21

In [75]:
#Reorganizing arrays
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [87]:
#Load data from file
filedata =np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [88]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [89]:
#Advanced indexing & boolean masking
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [90]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [91]:
#You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])